name: Publish to Test PyPI
on:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [prereleased]
jobs:
  # Before a release, run the test suite
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - name: Install Node dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Compile JavaScript
        run: |
          yarn build

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: pip

      - name: Install additional system packages
        run: |
          sudo apt-get update -y
          # Need `gettext` to compile translations
          sudo apt-get install gettext

      - name: Install Python dependencies
        run: pip install .[testing] build hatchling

      - name: Compile translations
        run: |
          /bin/sh ./scripts/compile_translations.sh

      - name: Build package distributions
        run: python -m build

      - uses: actions/upload-artifact@v6
        with:
          name: dist
          path: ./dist

  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  pypi-publish:
    needs: ["build"]
    environment: "pypi"

    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: dist
          path: ./dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist
          print-hash: true
          repository-url: https://test.pypi.org/legacy/
