name: Test & Lint
# Inspired by https://github.com/wagtail/wagtail-bakery/blob/0bfff2a7446e6119156279d22cfac2137960145d/.github/workflows/test.yml

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call: # Allow for the publish workflows to run the tests by calling this workflow

env:
  FORCE_COLOR: "1" # Make tools pretty.
  TOX_TESTENV_PASSENV: FORCE_COLOR
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  qa_javascript:
    name: Build JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Compile JavaScript
        run: |
          yarn build

  test_python:
    name: Test on Python ${{ matrix.python}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - uses: gerlero/apt-install@69d8f22493ec83ec5277cf2f661bd4d2fa88986e
        name: Install gettext
        with:
          packages: gettext

      - name: Install dependencies
        run: |
          python -m pip install .[testing] tox coverage

      - name: Compile translations
        run: /bin/sh ./scripts/compile_translations.sh

        # This step runs only for jobs NOT in the include matrix
      - name: Run tox targets for Python ${{ matrix.python }}
        run: |
          # Run only the tox environments that match the Python version
          tox run -f py$(echo ${{ matrix.python }} | tr -d .)
          coverage combine
          coverage report
          # Codecov does not support the .coverage file generated by coverage.
          # so we convert it to xml
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  e2e_tests:
    name: End-to-End Tests
    uses: ./.github/workflows/playwright-tests.yml
